# Generated by Django 5.0.3 on 2026-07-05 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar_position',
            field=models.CharField(choices=[('center', 'Center'), ('top', 'Top'), ('bottom', 'Bottom')], default='center', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar_ratio',
            field=models.CharField(choices=[('1-1', '1:1 (Square)'), ('4-5', '4:5 (Portrait)'), ('16-9', '16:9 (Landscape)'), ('auto', 'Auto / Original')], default='auto', max_length=10),
        ),
    ]
